Repository Techit-Springles/Backend, pull requests merged in 2023-08, with the labels that each got.

#15 [Feature] stomp + websocket 연결
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/springles/config/.keep
  src/main/java/com/springles/config/WebSocketConfig.java
  src/main/java/com/springles/controller/.keep
  src/main/java/com/springles/controller/ChatController.java
  src/main/java/com/springles/controller/ChatRoomController.java
  src/main/java/com/springles/domain/dto/Chat/ChatRoom.java
  src/main/java/com/springles/domain/dto/Chat/Message.java
  src/main/java/com/springles/service/ChatService.java
Labels: ⚙ Setting, ✨ Feature, 📑 Docs

#24 [Setting] ci 코드 작성
  docker/.mysql_env
Labels: 🔨 Chore

#25 [Setting] ci 코드 작성
  .github/workflows/deploy.yml
  .gitignore
Labels: 🔨 Chore, 🌏 Deploy

#27 [Setting] ci 코드 작성
  .github/workflows/deploy.yml
Labels: 🔨 Chore, 🐛 BugFix, 🌏 Deploy

#21 Feature/#13 list chatrooms
  src/main/java/com/springles/controller/ChatRoomController.java
  src/main/java/com/springles/domain/constants/ResponseCode.java
  src/main/java/com/springles/domain/dto/Chat/ChatRoomListResponseDto.java
  src/main/java/com/springles/repository/ChatRoomJpaRepository.java
  src/main/java/com/springles/repository/MemberRepository.java
  src/main/java/com/springles/repository/custom/MemberCustomRepository.java
  src/main/java/com/springles/repository/impl/MemberRepositoryImpl.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
Labels: ✨ Feature, 🎆 API

#23 [Featrue] 레디스를 이용한 기본채팅 구현
  build.gradle
  src/main/java/com/springles/config/RedisConfig.java
  src/main/java/com/springles/config/WebSocketConfig.java
  src/main/java/com/springles/controller/ChatController.java
  src/main/java/com/springles/controller/ChatMessageController.java
  src/main/java/com/springles/controller/ChatRoomController.java
  src/main/java/com/springles/domain/dto/Chat/ChatRoom.java
  src/main/java/com/springles/domain/dto/Chat/Message.java
  src/main/java/com/springles/domain/dto/chat/MessageRequestDto.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomReqDTO.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomResponseDto.java
  src/main/java/com/springles/redis/ChatMessage.java
  src/main/java/com/springles/redis/Redisroom.java
  src/main/java/com/springles/redis/Subscriber.java
  src/main/java/com/springles/repository/ChatRoomRedisRepository.java
  src/main/java/com/springles/repository/ChatRoomRepository.java
  src/main/java/com/springles/repository/impl/ChatRoomRepositoryImpl.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/ChatService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/springles/service/impl/ChatServiceImpl.java
Labels: ✨ Feature, 🎆 API

#34 [Setting] HOTFIX build gradle
  build.gradle
Labels: 🔨 Chore, 🐛 BugFix, 🌏 Deploy

#38 Setting/#31-Key-Name
  .github/workflows/deploy.yml
Labels: 🔨 Chore, 🌏 Deploy

#40 [Setting] ci: <CI 버전>
  .github/workflows/deploy.yml
Labels: 🔨 Chore, 🐛 BugFix, 🌏 Deploy

#42 👷 ci: <CI 만 살려 두기>
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#37 Test/#22 chatroom list test code
  .ebextensions/00-makeFiles.config
  .github/workflows/deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/test/java/com/springles/controller/ChatRoomControllerTest.java
  src/test/java/com/springles/repository/ChatRoomJpaRepositoryTest.java
  src/test/java/com/springles/repository/MemberRepositoryTest.java
  src/test/java/com/springles/service/impl/ChatRoomServiceImplTest.java
Labels: ✅ Test

#39 Feature/#19 validation exception
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomReqDTO.java
  src/main/java/com/springles/exception/ErrorResponse.java
  src/main/java/com/springles/exception/GlobalExceptionHandler.java
  src/main/java/com/springles/exception/constants/ErrorCode.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
Labels: ⚙ Setting, 🔧 Refactor, 🎆 API

#52 🚚 chore: <.gitignore 추가>
  .gitignore
  src/main/java/com/springles/controller/ui/ChatUiController.java
Labels: ⚙ Setting

#53 Feature/#43 chatroom update
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/domain/constants/ResponseCode.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomResponseDto.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomUpdateReqDto.java
  src/main/java/com/springles/domain/entity/ChatRoom.java
  src/main/java/com/springles/exception/constants/ErrorCode.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
Labels: ✨ Feature, 🎆 API

#55 feat: 채팅방 삭제 API
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/domain/constants/ResponseCode.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
Labels: ✨ Feature, 🎆 API

#61 Feature/#50 vertification id pw
  build.gradle
  src/main/java/com/springles/config/MailConfig.java
  src/main/java/com/springles/controller/api/MemberController.java
  src/main/java/com/springles/domain/constants/ResponseCode.java
  src/main/java/com/springles/domain/dto/member/MemberVertifIdRequest.java
  src/main/java/com/springles/domain/dto/member/MemberVertifPwRequest.java
  src/main/java/com/springles/exception/constants/ErrorCode.java
  src/main/java/com/springles/repository/MemberJpaRepository.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/application-mail.yml
  src/main/resources/application.yml
Labels: ✨ Feature, 🎆 API

#62 [Feat] web socket config handler
  build.gradle
  src/main/java/com/springles/config/RedisConfig.java
  src/main/java/com/springles/config/WebSocketConfig.java
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/controller/api/ChatMessageController.java
  src/main/java/com/springles/controller/ui/ChatUiController.java
  src/main/java/com/springles/domain/dto/chatting/MessageRequestDto.java
  src/main/java/com/springles/redis/ChatMessage.java
  src/main/java/com/springles/redis/Redisroom.java
  src/main/java/com/springles/redis/Subscriber.java
  src/main/java/com/springles/repository/ChatRoomRedisRepository.java
  src/main/java/com/springles/service/ChatService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/springles/service/impl/ChatServiceImpl.java
  src/main/java/com/springles/websocket/SimpleChatHandler.java
  src/main/java/com/springles/websocket/WebSocketMapping.java
  src/main/resources/application-redis.yml
  src/main/resources/static/js/stomp.js
  src/main/resources/templates/chat-lobby.html
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/chat.html
  src/main/resources/templates/rooms.html
Labels: ⚙ Setting, 🔨 Chore, ✨ Feature

#65 [Refactor] member repository
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
Labels: 🔧 Refactor

#66 Feature/#57 chatrooms thymeleaf
  df
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomReqDTO.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomResponseDto.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomUpdateReqDto.java
  src/main/java/com/springles/domain/entity/ChatRoom.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/resources/static/css/basic.css
  src/main/resources/static/h.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home.html
  src/main/resources/templates/home/add.html
  src/main/resources/templates/home/index.html
  src/main/resources/templates/layouts/basic.html
  src/test/java/com/springles/repository/ChatRoomJpaRepositoryTest.java
Labels: ✨ Feature

#75 Fix/#72 mailconfig circular reference
  src/main/java/com/springles/config/MailConfig.java
  src/main/resources/application-mail.yml
  src/main/resources/application.yml
Labels: 🐛 BugFix

#77 [Feat] 채팅방 공유하기 버튼 추가
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/controller/ui/ChatUiController.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomReqDTO.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomResponseDto.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomUpdateReqDto.java
  src/main/java/com/springles/domain/entity/ChatRoom.java
  src/main/java/com/springles/repository/custom/ChatRoomCustomRepository.java
  src/main/java/com/springles/repository/impl/ChatRoomRepositoryImpl.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/resources/static/css/basic.css
  src/main/resources/templates/chat-room-info.html
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home/add.html
  src/main/resources/templates/home/index.html
  src/main/resources/templates/layouts/basic.html
  src/main/resources/templates/pages/chatting/chatting.html
  src/main/resources/templates/pages/home/home.html
Labels: ✨ Feature

#81 [Setting]#80 redis setting
  build.gradle
  src/main/java/com/springles/config/RedisConfig.java
Labels: ⚙ Setting

#85 :sparkles: feat: <채팅방 목록 생성, url 연결>
  src/main/java/com/springles/config/RedisConfig.java
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomReqDTO.java
  src/main/java/com/springles/domain/dto/chatting/ChatRoomListResponseDto.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/resources/application-redis.yml
  src/main/resources/templates/home/add.html
  src/main/resources/templates/home/index.html
  src/main/resources/templates/home/list.html
Labels: ✨ Feature, 🎆 API

#88 Feature/#86-회원가입-로그인-로그아웃-페이지-생성
  src/main/java/com/springles/config/WebSecurityConfig.java
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/controller/ui/MemberUiController.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/sign-up.html
Labels: ✨ Feature, 🎆 API

#92 [Feature] 게임 로직 구현 - 임시 병합
  src/main/java/com/springles/config/RedisConfig.java
  src/main/java/com/springles/controller/api/RefreshTokenContoller.java
  src/main/java/com/springles/domain/constants/GamePhase.java
  src/main/java/com/springles/domain/constants/GameRole.java
  src/main/java/com/springles/domain/constants/GameRoleNum.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomResponseDto.java
  src/main/java/com/springles/domain/dto/member/MemberUpdateRequest.java
  src/main/java/com/springles/domain/entity/GameSession.java
  src/main/java/com/springles/domain/entity/Player.java
  src/main/java/com/springles/domain/entity/RefreshToken.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/game/RoleManager.java
  src/main/java/com/springles/redisPubSub/Publisher.java
  src/main/java/com/springles/repository/GameSessionRedisRepository.java
  src/main/java/com/springles/repository/PlayerRedisRepository.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/test/java/com/springles/repository/ChatRoomJpaRepositoryTest.java
  src/test/java/com/springles/repository/MemberRepositoryTest.java
Labels: ✨ Feature, 🎆 API

#90 :sparkles: feature/#89-게임방-목록-및-검색-ui
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/domain/dto/chatting/ChatRoomListResponseDto.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/resources/templates/home/list.html
Labels: ✨ Feature, 🎆 API

#94 [Fix] Redis Hash Id 어노테이션 수정
  src/main/java/com/springles/domain/entity/GameSession.java
  src/main/java/com/springles/domain/entity/Player.java
Labels: 🐛 BugFix

#98 :bug: fix: <close 필드 자료형 수정>
  src/main/java/com/springles/config/WebSecurityConfig.java
  src/main/java/com/springles/domain/dto/chatting/ChatRoomListResponseDto.java
  src/main/resources/templates/fragments/header.html
Labels: 🐛 BugFix

#95 Test/#63 signup login
  src/main/java/com/springles/config/MailConfig.java
  src/main/java/com/springles/controller/api/RefreshTokenContoller.java
  src/main/java/com/springles/domain/dto/member/MemberCreateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberDeleteRequest.java
  src/main/java/com/springles/domain/dto/member/MemberLoginRequest.java
  src/main/java/com/springles/domain/dto/member/MemberUpdateRequest.java
  src/test/java/com/springles/controller/MemberControllerTest.java
  src/test/java/com/springles/controller/RefreshTokenContollerTest.java
  src/test/java/com/springles/repository/BlackListTokenRedisRepositoryTest.java
  src/test/java/com/springles/repository/MemberJpaRepositoryTest.java
  src/test/java/com/springles/repository/MemberRepositoryTest.java
  src/test/java/com/springles/repository/RefreshTokenRedisRepositoryTest.java
  src/test/java/com/springles/service/impl/MemberServiceImplTest.java
  src/test/java/com/springles/service/impl/RefreshTokenServiceImplTest.java
Labels: ✅ Test

#100 Feature/#96 profile create read update
  src/main/java/com/springles/controller/api/MemberController.java
  src/main/java/com/springles/domain/constants/ProfileImg.java
  src/main/java/com/springles/domain/constants/ResponseCode.java
  src/main/java/com/springles/domain/dto/member/MemberProfileCreateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberProfileRead.java
  src/main/java/com/springles/domain/dto/member/MemberProfileResponse.java
  src/main/java/com/springles/domain/dto/member/MemberProfileUpdateRequest.java
  src/main/java/com/springles/domain/entity/MemberGameInfo.java
  src/main/java/com/springles/repository/support/MemberGameInfoJpaRepository.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/static/images/profile_01.jpg
  src/main/resources/static/images/profile_02.jpg
  src/main/resources/static/images/profile_03.jpg
  src/main/resources/static/images/profile_04.jpg
  src/main/resources/static/images/profile_05.jpg
  src/main/resources/static/images/profile_06.jpg
Labels: 🎆 API

#101 Feature/#91 token header
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/controller/ui/MemberUiController.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomReqDTO.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomResponseDto.java
  src/main/java/com/springles/domain/dto/chatting/ChatRoomListResponseDto.java
  src/main/java/com/springles/domain/dto/member/MemberInfoResponse.java
  src/main/java/com/springles/domain/entity/GameSession.java
  src/main/java/com/springles/domain/entity/Player.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home/add.html
  src/main/resources/templates/home/list.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/sign-up.html
Labels: ✨ Feature, 🎆 API, 🙋‍♂️ Question

#108 [Docs] 풀리퀘스트 템플릿 위치 변경
  .github/pull_request_template.md
Labels: 📑 Docs

#111 Fix/#110-requestDto-add-setter
  src/main/java/com/springles/domain/dto/member/MemberCreateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberDeleteRequest.java
  src/main/java/com/springles/domain/dto/member/MemberLoginRequest.java
  src/main/java/com/springles/domain/dto/member/MemberProfileCreateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberProfileUpdateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberUpdateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberVertifIdRequest.java
  src/main/java/com/springles/domain/dto/member/MemberVertifPwRequest.java
Labels: 🐛 BugFix

#107 [Feature] 게임 진행 로직 개발
  src/main/java/com/springles/domain/constants/GameRoleNum.java
  src/main/java/com/springles/domain/entity/GameSession.java
  src/main/java/com/springles/exception/CustomException.java
  src/main/java/com/springles/exception/constants/ErrorCode.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/game/RoleManager.java
  src/main/java/com/springles/repository/GameSessionRedisRepository.java
  src/test/java/com/springles/game/GameSessionManagerTest.java
Labels: ✨ Feature, ✅ Test

#109 Feat/#82 voting
  src/main/java/com/springles/domain/dto/game/VoteDto.java
  src/main/java/com/springles/domain/entity/Vote.java
  src/main/java/com/springles/domain/entity/VoteInfo.java
  src/main/java/com/springles/repository/VoteRedisRepository.java
  src/main/java/com/springles/repository/VoteRepository.java
Labels: ✨ Feature, 🎆 API

#112 Feature/#103 levelup
  src/main/java/com/springles/controller/api/MemberController.java
  src/main/java/com/springles/domain/constants/GameRole.java
  src/main/java/com/springles/domain/constants/Level.java
  src/main/java/com/springles/domain/constants/ResponseCode.java
  src/main/java/com/springles/domain/dto/member/MemberProfileCreateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberProfileRead.java
  src/main/java/com/springles/domain/dto/member/MemberProfileResponse.java
  src/main/java/com/springles/domain/entity/GameRecord.java
  src/main/java/com/springles/domain/entity/MemberGameInfo.java
  src/main/java/com/springles/exception/constants/ErrorCode.java
  src/main/java/com/springles/repository/GameRecordJpaRepository.java
  src/main/java/com/springles/repository/support/MemberGameInfoJpaRepository.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
Labels: 🐛 BugFix, 🎆 API

#117 HOTFIX 의존성 주입 문제 해결
  src/main/java/com/springles/config/RedisConfig.java
  src/main/java/com/springles/domain/dto/game/VoteDto.java
  src/main/java/com/springles/domain/entity/Vote.java
  src/main/java/com/springles/domain/entity/VoteInfo.java
  src/main/java/com/springles/repository/VoteRedisRepository.java
  src/main/java/com/springles/repository/VoteRepository.java
Labels: 🐛 BugFix

#123 Test/#122 mypage
  src/test/java/com/springles/controller/MemberControllerTest.java
  src/test/java/com/springles/repository/GameRecordJpaRepositoryTest.java
  src/test/java/com/springles/repository/MemberGameInfoJpaRepositoryTest.java
  src/test/java/com/springles/repository/MemberRecordJpaRepositoryTest.java
  src/test/java/com/springles/service/impl/MemberServiceImplTest.java
  src/test/java/com/springles/service/impl/RefreshTokenServiceImplTest.java
Labels: ✅ Test, 🐛 BugFix

#129 [Feature] 채팅 로직 메세지 컨트롤러 개발 (중간 PR)
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/domain/dto/chatting/MessageRequestDto.java
  src/main/java/com/springles/domain/entity/Player.java
  src/main/java/com/springles/game/ChatMessage.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/game/MessageInterceptor.java
  src/main/java/com/springles/redisPubSub/Publisher.java
  src/main/java/com/springles/repository/PlayerRedisRepository.java
  src/main/java/com/springles/websocket/WebSocketMapping.java
  src/test/java/com/springles/game/GameSessionManagerTest.java
Labels: ✨ Feature, 🎆 API

#130 [Feature] 랜덤 매칭
  src/main/java/com/springles/controller/ui/ChatUiController.java
  src/main/java/com/springles/exception/constants/ErrorCode.java
  src/main/java/com/springles/repository/ChatRoomJpaRepository.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/resources/templates/chat-room-info.html
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/check/confirm.html
  src/main/resources/templates/home/index.html
Labels: ✨ Feature, 🎆 API

#126 Feature/#119 mainpage UI
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/controller/ui/ChatUiController.java
  src/main/java/com/springles/controller/ui/MemberUiController.java
  src/main/java/com/springles/domain/dto/member/MemberInfoResponse.java
  src/main/resources/static/css/basic.css
  src/main/resources/static/images/lock.png
  src/main/resources/static/images/profile.png
  src/main/resources/static/images/search.png
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home/add.html
  src/main/resources/templates/home/index.html
  src/main/resources/templates/home/list.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/sign-up.html
Labels: 🎨 Frontend

#125 Feat/#114 vote logic
  src/main/java/com/springles/config/TimeConfig.java
  src/main/java/com/springles/config/WebSocketConfig.java
  src/main/java/com/springles/controller/ui/ChatUiController.java
  src/main/java/com/springles/domain/dto/game/GameSessionVoteRequest.java
  src/main/java/com/springles/domain/entity/GameSession.java
  src/main/java/com/springles/domain/entity/Player.java
  src/main/java/com/springles/exception/constants/ErrorCode.java
  src/main/java/com/springles/game/task/VoteFinTimerTask.java
  src/main/java/com/springles/repository/VoteRedisRepository.java
  src/main/java/com/springles/repository/VoteRepository.java
  src/main/java/com/springles/service/GameSessionVoteService.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
  src/main/java/com/springles/websocket/SimpleChatHandler.java
Labels: ✨ Feature, 🔧 Refactor

#134 [Fix] #133 bug fix
  src/main/java/com/springles/controller/ui/ChatUiController.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
Labels: 🐛 BugFix

#139 Feature/#127 chatroom UI
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/controller/ui/ChatUiController.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/resources/static/css/basic.css
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/home/add.html
  src/main/resources/templates/layouts/basic.html
  src/main/resources/templates/member/sign-up.html
  src/test/java/com/springles/controller/MemberControllerTest.java
Labels: 🎨 Frontend

#137 [Feature]#106 랜덤방, 비밀방 입장
  src/main/java/com/springles/domain/dto/chatting/ChatRoomListResponseDto.java
  src/main/resources/templates/home/index.html
Labels: 🎆 API

#140 [Refactor] 페이지 → 스크롤로 변경
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/repository/custom/ChatRoomCustomRepository.java
  src/main/java/com/springles/repository/impl/ChatRoomRepositoryImpl.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/resources/templates/fragments/page.html
  src/main/resources/templates/home/index.html
  src/main/resources/templates/home/list.html
  src/test/java/com/springles/controller/ChatRoomControllerTest.java
  src/test/java/com/springles/repository/ChatRoomJpaRepositoryTest.java
  src/test/java/com/springles/service/impl/ChatRoomServiceImplTest.java
Labels: 🔧 Refactor, 🎨 Frontend

#143 Fix/#136 security filter logic
  src/main/java/com/springles/config/WebSecurityConfig.java
  src/main/java/com/springles/controller/api/RefreshTokenContoller.java
  src/main/java/com/springles/controller/ui/MemberUiController.java
  src/main/java/com/springles/game/MessageInterceptor.java
  src/main/java/com/springles/jwt/AccessTokenInterceptor.java
  src/main/java/com/springles/jwt/JwtExceptionHandlerFilter.java
  src/main/java/com/springles/jwt/JwtTokenFilter.java
  src/main/java/com/springles/jwt/JwtTokenUtils.java
  src/main/java/com/springles/service/RefreshTokenService.java
  src/main/java/com/springles/service/impl/RefreshTokenServiceImpl.java
Labels: ✨ Feature, 🐛 BugFix

#147 :construction_worker: ci: <deploy>
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/game/task/VoteFinTimerTask.java
  src/test/java/com/springles/game/GameSessionVoteServiceTest.java
Labels: 🌏 Deploy
