Repository Techit-Springles/Backend, pull requests merged in 2023-09, with the labels that each got.

#150 [Refactor] chatroomListResponseDto -> chatroomResponseDto 로 변경
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomResponseDto.java
  src/main/java/com/springles/domain/dto/chatting/ChatRoomListResponseDto.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/test/java/com/springles/service/impl/ChatRoomServiceImplTest.java
Labels: 🔧 Refactor

#152 Feature/#144 frontend authority
  .github/pull_request_template.md
  src/main/java/com/springles/config/LoginFailureHandler.java
  src/main/java/com/springles/config/LoginSuccessHandler.java
  src/main/java/com/springles/config/WebSecurityConfig.java
  src/main/java/com/springles/controller/ui/MemberUiController.java
  src/main/java/com/springles/jwt/JwtExceptionFilter.java
  src/main/java/com/springles/jwt/JwtTokenFilter.java
  src/main/java/com/springles/jwt/JwtTokenUtils.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/member/login.html
Labels: ✨ Feature, 🎆 API

#154 :recycle: refactor: <Exception 메시지 통일>
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/exception/ErrorResponse.java
  src/main/java/com/springles/exception/GlobalExceptionHandler.java
  src/main/java/com/springles/exception/constants/ErrorCode.java
Labels: 🔧 Refactor

#156 :sparkles: feat: MessageManager 생성
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/domain/constants/ResponseCode.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/game/MessageManager.java
Labels: ✨ Feature

#160 :recycle: refactor: <ui controller 대신 api controller 호출로 수정>
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/resources/templates/home/add.html
Labels: 🔧 Refactor

#159 Feature/#118 chat room game session union
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/repository/ChatRoomJpaRepository.java
  src/main/java/com/springles/repository/custom/ChatRoomCustomRepository.java
  src/main/java/com/springles/repository/custom/MemberCustomRepository.java
  src/main/java/com/springles/repository/impl/ChatRoomRepositoryImpl.java
  src/main/java/com/springles/repository/impl/MemberRepositoryImpl.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
Labels: ✨ Feature, 🎆 API

#161 [Fix] QueryDsl 레포지토리명 수정
  src/main/java/com/springles/repository/ChatRoomJpaRepository.java
  src/main/java/com/springles/repository/MemberJpaRepository.java
  src/main/java/com/springles/repository/custom/ChatRoomJpaRepositoryCustom.java
  src/main/java/com/springles/repository/custom/MemberJpaRepositoryCustom.java
  src/main/java/com/springles/repository/impl/ChatRoomJpaRepositoryImpl.java
  src/main/java/com/springles/repository/impl/MemberJpaRepositoryImpl.java
Labels: 🐛 BugFix

#162 [Feature] 채팅 선별 기능 추가
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/repository/custom/.keep
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
Labels: ✨ Feature

#164 Feat/#141 game logic change
  src/main/java/com/springles/config/TimeConfig.java
  src/main/java/com/springles/domain/constants/GamePhase.java
  src/main/java/com/springles/domain/dto/message/DayDiscussionMessage.java
  src/main/java/com/springles/domain/dto/message/DayEliminationMessage.java
  src/main/java/com/springles/domain/dto/message/NightVoteMessage.java
  src/main/java/com/springles/domain/dto/response/GameStatus.java
  src/main/java/com/springles/domain/dto/response/GameStatusKill.java
  src/main/java/com/springles/domain/dto/response/GameStatusKillRes.java
  src/main/java/com/springles/domain/dto/response/GameStatusRes.java
  src/main/java/com/springles/domain/dto/response/PlayerDeadRes.java
  src/main/java/com/springles/domain/dto/response/PlayerStatus.java
  src/main/java/com/springles/domain/entity/GameSession.java
  src/main/java/com/springles/domain/entity/Player.java
  src/main/java/com/springles/game/DayDiscussionManager.java
  src/main/java/com/springles/game/DayEliminationManager.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
Labels: ✨ Feature

#165 Feature/#153 member mypage UI
  src/main/java/com/springles/controller/ui/MemberUiController.java
  src/main/java/com/springles/domain/constants/ProfileImg.java
  src/main/java/com/springles/domain/dto/member/MemberInfoResponse.java
  src/main/java/com/springles/domain/dto/member/MemberRecordResponse.java
  src/main/java/com/springles/domain/entity/MemberRecord.java
  src/main/java/com/springles/game/DayEliminationManager.java
  src/main/java/com/springles/repository/MemberGameInfoJpaRepository.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/static/css/basic.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/member-info.html
  src/main/resources/templates/member/member-sign-out.html
  src/main/resources/templates/member/my-page.html
  src/main/resources/templates/member/profile-change.html
  src/main/resources/templates/member/profile-settings.html
  src/main/resources/templates/member/sign-up.html
  src/main/resources/templates/member/vertification-id.html
  src/main/resources/templates/member/vertification-pw.html
Labels: 🐛 BugFix, 🎨 Frontend

#170 [Feat] #166 night vote
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/domain/constants/GamePhase.java
  src/main/java/com/springles/domain/dto/message/NightVoteMessage.java
  src/main/java/com/springles/domain/dto/response/PlayerDeadRes.java
  src/main/java/com/springles/domain/dto/response/SuspectVoteRes.java
  src/main/java/com/springles/exception/constants/ErrorCode.java
  src/main/java/com/springles/game/DayEliminationManager.java
  src/main/java/com/springles/game/NightVoteManager.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
Labels: ✨ Feature

#168 :sparkles: feat: 프로필정보 db와 연동, 아이디 -> 닉네임으로 변경
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/static/css/basic.css
  src/main/resources/templates/home/index.html
Labels: ✨ Feature, 🎨 Frontend

#173 :bug: fix: controller 코드 추가
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/controller/ui/MemberUiController.java
Labels: 🐛 BugFix

#174 [FIX] 오탈자 수정
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/game/DayEliminationManager.java
Labels: 🐛 BugFix

#180 :sparkles: feat: 로그아웃 프론트 기능 구현
  src/main/java/com/springles/controller/ui/MemberUiController.java
  src/main/java/com/springles/jwt/JwtTokenFilter.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/templates/fragments/header.html
Labels: ✨ Feature, 🎨 Frontend

#182 Fix/#181 mypage member record odds
  src/main/java/com/springles/domain/dto/member/MemberRecordResponse.java
Labels: 🐛 BugFix

#184 Feat/#179 suspect individual
  src/main/java/com/springles/domain/dto/message/NightVoteMessage.java
  src/main/java/com/springles/game/NightVoteManager.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
  src/test/java/com/springles/game/GameSessionVoteServiceTest.java
Labels: ✨ Feature

#188 Fix/#187-index-redirect-error
  src/main/java/com/springles/jwt/JwtTokenFilter.java
Labels: 🐛 BugFix

#189 [feat] <startVote 만들기>
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/domain/entity/GameSession.java
Labels: ✨ Feature

#190 [feat] <일단 채팅을 만들자>
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/websocket/WebSocketMapping.java
  src/main/resources/application-dev.yml
  src/main/resources/data.sql
  src/main/resources/templates/chat-room.html
Labels: 🎨 Frontend

#191 Feature/#176 player list websocket
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/game/MessageInterceptor.java
  src/main/java/com/springles/game/MessageManager.java
Labels: ✨ Feature

#195 :bug: fix: <채팅방 중복 생성 오류 해결>
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
Labels: 🐛 BugFix

#196 :recycle: refactor: <채팅방 생성 후 채팅방 url로 이동하도록 수정>
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomCreateResponseDto.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/resources/templates/home/add.html
Labels: 🔧 Refactor

#199 Feature/#183 member mypage fnd exception
  src/main/java/com/springles/controller/api/MemberController.java
  src/main/java/com/springles/controller/ui/MemberUiController.java
  src/main/java/com/springles/domain/dto/member/MemberCreateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberDeleteRequest.java
  src/main/java/com/springles/domain/dto/member/MemberLoginRequest.java
  src/main/java/com/springles/domain/dto/member/MemberProfileCreateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberProfileUpdateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberUpdateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberVertifIdRequest.java
  src/main/java/com/springles/domain/dto/member/MemberVertifPwRequest.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/java/com/springles/valid/ValidationGroups.java
  src/main/java/com/springles/valid/ValidationSequence.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/member-info.html
  src/main/resources/templates/member/member-sign-out.html
  src/main/resources/templates/member/profile-change.html
  src/main/resources/templates/member/profile-settings.html
  src/main/resources/templates/member/sign-up.html
  src/main/resources/templates/member/vertification-id.html
  src/main/resources/templates/member/vertification-pw.html
Labels: ✨ Feature, 🔧 Refactor, 🎨 Frontend

#201 [Feature] 채팅방 - 게임 세션 생성 API 연동
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/game/MessageInterceptor.java
  src/main/java/com/springles/jwt/JwtTokenFilter.java
  src/main/java/com/springles/jwt/JwtTokenUtils.java
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/home/add.html
Labels: ✨ Feature, 🎆 API

#202 Feature/#197 secret room enter modal
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/resources/static/css/basic.css
  src/main/resources/templates/home/add.html
  src/main/resources/templates/home/index.html
Labels: ✨ Feature, 🐛 BugFix, 🎨 Frontend

#205 Feature/#177 front chatting stomp
  src/main/java/com/springles/domain/entity/ChatRoom.java
  src/main/java/com/springles/domain/entity/GameSession.java
  src/main/java/com/springles/domain/entity/Player.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/game/MessageManager.java
  src/main/java/com/springles/repository/GameSessionRedisRepository.java
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/home/add.html
  src/test/java/com/springles/controller/MemberControllerTest.java
  src/test/java/com/springles/controller/RefreshTokenContollerTest.java
  src/test/java/com/springles/repository/ChatRoomJpaRepositoryTest.java
  src/test/java/com/springles/repository/MemberJpaRepositoryTest.java
  src/test/java/com/springles/service/impl/MemberServiceImplTest.java
  src/test/java/com/springles/service/impl/RefreshTokenServiceImplTest.java
Labels: ✨ Feature, 🐛 BugFix, 🎨 Frontend

#209 [Feature] 채팅방 입장, 퇴장 메시지 출력 + 참여자 목록 실시간 변동 추가
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/domain/dto/message/RoleExplainMessage.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/resources/data.sql
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/home/add.html
Labels: ✨ Feature, 🎆 API, 🎨 Frontend

#210 Feat/#206 vote connect 중간 pr
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/repository/VoteRedisRepository.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/templates/chat-room.html
Labels: 🎨 Frontend

#211 Fix/#200 jwt token filter logic
  src/main/java/com/springles/config/WebSecurityConfig.java
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/controller/api/MemberController.java
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/controller/ui/ChatUiController.java
  src/main/java/com/springles/controller/ui/MemberUiController.java
  src/main/java/com/springles/jwt/JwtTokenFilter.java
  src/main/java/com/springles/jwt/JwtTokenUtils.java
Labels: 🐛 BugFix

#214 Fix/#212 logout error
  src/main/java/com/springles/exception/constants/ErrorCode.java
  src/main/java/com/springles/jwt/JwtExceptionFilter.java
  src/main/java/com/springles/jwt/JwtTokenFilter.java
  src/main/resources/templates/fragments/header.html
Labels: 🐛 BugFix

#217 Cicd/#213 2 code change for cicd
  src/main/resources/application-dev.yml
  src/main/resources/templates/chat-room-info.html
  src/test/java/com/springles/game/GameSessionManagerTest.java
  src/test/java/com/springles/repository/MemberRecordJpaRepositoryTest.java
Labels: 🐛 BugFix, 🌏 Deploy

#220 Feature/#177 front game ing
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/domain/constants/GameRole.java
  src/main/java/com/springles/domain/dto/message/RoleExplainMessage.java
  src/main/java/com/springles/domain/entity/ChatRoom.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature, 🎨 Frontend

#221 :sparkles: feat: <낮 투표 기능 완>
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/domain/entity/GameSession.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature, 🎨 Frontend

#222 Feature/#215 entity relationship
  src/main/java/com/springles/domain/dto/member/MemberProfileCreateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberProfileResponse.java
  src/main/java/com/springles/domain/dto/member/MemberProfileUpdateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberRecordResponse.java
  src/main/java/com/springles/domain/entity/GameRecord.java
  src/main/java/com/springles/domain/entity/Member.java
  src/main/java/com/springles/domain/entity/MemberGameInfo.java
  src/main/java/com/springles/domain/entity/MemberRecord.java
  src/main/java/com/springles/repository/GameRecordJpaRepository.java
  src/main/java/com/springles/repository/MemberGameInfoJpaRepository.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/springles/repository/GameRecordJpaRepositoryTest.java
  src/test/java/com/springles/repository/MemberGameInfoJpaRepositoryTest.java
  src/test/java/com/springles/repository/MemberRecordJpaRepositoryTest.java
Labels: ✨ Feature

#226 Refactor/#223 login mypage apicontroller call
  src/main/java/com/springles/config/WebSecurityConfig.java
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/controller/api/CookieController.java
  src/main/java/com/springles/controller/api/MemberController.java
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/controller/ui/ChatUiController.java
  src/main/java/com/springles/controller/ui/MemberUiController.java
  src/main/java/com/springles/domain/constants/ResponseCode.java
  src/main/java/com/springles/domain/dto/cookie/CookieSetRequest.java
  src/main/java/com/springles/jwt/JwtTokenFilter.java
  src/main/java/com/springles/jwt/JwtTokenUtils.java
  src/main/java/com/springles/repository/MemberGameInfoJpaRepository.java
  src/main/java/com/springles/service/CookieService.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/CookieServiceImpl.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/templates/member/login.html
Labels: 🔧 Refactor

#230 deploy.yml --> secrets: inherit 추가
  .github/workflows/deploy.yml
Labels: 🔨 Chore

#233 Refactor/#227 mypage apicontroller call
  src/main/java/com/springles/controller/api/MemberController.java
  src/main/java/com/springles/controller/ui/MemberUiController.java
  src/main/java/com/springles/domain/constants/ProfileImg.java
  src/main/java/com/springles/domain/dto/member/MemberProfileRead.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/templates/home/index.html
  src/main/resources/templates/member/member-info.html
  src/main/resources/templates/member/my-page.html
  src/main/resources/templates/member/profile-change.html
Labels: 🔧 Refactor

#235 Feat/#225 vote confirm and kill
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/domain/entity/GameSession.java
  src/main/java/com/springles/game/DayDiscussionManager.java
  src/main/java/com/springles/game/DayEliminationManager.java
  src/main/java/com/springles/game/DayToNightManager.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature, 🎨 Frontend

#238 Feature/#234 member fnd develop
  src/main/java/com/springles/domain/constants/Level.java
  src/main/java/com/springles/domain/dto/member/MemberProfileRead.java
  src/main/java/com/springles/domain/dto/member/MemberSimpleProfileResponse.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/static/css/basic.css
  src/main/resources/static/images/icon_lv_info_btn.png
  src/main/resources/static/images/level/ASSOCIATE.png
  src/main/resources/static/images/level/BEGINNER.png
  src/main/resources/static/images/level/BOSS.png
  src/main/resources/static/images/level/CAPTAIN.png
  src/main/resources/static/images/level/SOLDIER.png
  src/main/resources/static/images/level/UNDERBOSS.png
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/home/add.html
  src/main/resources/templates/home/index.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/member-info.html
  src/main/resources/templates/member/member-sign-out.html
  src/main/resources/templates/member/my-page.html
  src/main/resources/templates/member/profile-change.html
  src/main/resources/templates/member/profile-settings.html
  src/main/resources/templates/member/sign-up.html
  src/main/resources/templates/member/vertification-id.html
  src/main/resources/templates/member/vertification-pw.html
Labels: 🎨 Frontend

#240 Fix/#239-accessToken-reissue-cookie-save-error
  src/main/java/com/springles/jwt/JwtTokenFilter.java
Labels: 🐛 BugFix

#242 Fix/#240 simple profile api extract atk
  src/main/java/com/springles/controller/api/MemberController.java
Labels: 🐛 BugFix

#248 Refactor/#247 chatroom enter
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/controller/ui/ChatUiController.java
  src/main/java/com/springles/domain/constants/ResponseCode.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/resources/templates/chat-lobby.html
  src/main/resources/templates/chat-room-info.html
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/home/add.html
  src/main/resources/templates/home/index.html
  src/main/resources/templates/home/list.html
Labels: 🔧 Refactor

#250 Feature/#249 mainpage design
  src/main/resources/static/css/basic.css
  src/main/resources/templates/home/index.html
Labels: 🎨 Frontend

#251 Cicd/#213 5 delpoy edit
  .github/workflows/deploy.yml
  build.gradle
Labels: 🔨 Chore, 🐛 BugFix

#253 Feat/#246 time control test
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/game/DayDiscussionManager.java
Labels: ✨ Feature, 🔧 Refactor

#255 Feature/#254 mypage form UI
  src/main/resources/static/css/basic.css
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/home/add.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/member-info.html
  src/main/resources/templates/member/member-sign-out.html
  src/main/resources/templates/member/my-page.html
  src/main/resources/templates/member/profile-change.html
  src/main/resources/templates/member/profile-settings.html
  src/main/resources/templates/member/sign-up.html
  src/main/resources/templates/member/vertification-id.html
  src/main/resources/templates/member/vertification-pw.html
Labels: 🎨 Frontend

#258 Feature/#257 page design
  src/main/resources/static/css/basic.css
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/home/index.html
Labels: 🎨 Frontend

#259 Feat/#236 night vote input
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/game/DayDiscussionManager.java
  src/main/java/com/springles/game/DayEliminationManager.java
  src/main/java/com/springles/game/DayToNightManager.java
  src/main/java/com/springles/service/GameSessionVoteService.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature, 🎨 Frontend

#245 [Feature] 게임 통합 로직 진행중
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/domain/constants/GamePhase.java
  src/main/java/com/springles/exception/GameEndException.java
  src/main/java/com/springles/game/DayDiscussionManager.java
  src/main/java/com/springles/game/DayToNightManager.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/resources/data.sql
Labels: ✨ Feature, 🎨 Frontend

#261 :bug: fix: <hot fix>
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/resources/templates/chat-room.html
Labels: 🐛 BugFix

#262 :bug: fix: 채팅 메시지 겹침 수정
  src/main/java/com/springles/controller/message/MessageController.java
Labels: 🐛 BugFix

#265 <fix: 채팅방 목록 List 수정>
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/home/index.html
Labels: 🐛 BugFix

#267 :sparkles: feat: <밤 투표 타이머 연결>
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/game/DayToNightManager.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature, 🎨 Frontend

#269 :bug: fix: 투표 리스트가 비어있을 떄 게임이 진행되지 않던 버그 수정
  src/main/java/com/springles/game/DayDiscussionManager.java
Labels: 🐛 BugFix

#271 ui:<chatroom playerlist dto add>
  src/main/java/com/springles/controller/api/MemberController.java
  src/main/java/com/springles/domain/dto/member/PlayerInfoRequest.java
  src/main/java/com/springles/domain/dto/member/PlayerInfoResponse.java
  src/main/java/com/springles/repository/custom/ChatRoomJpaRepositoryCustom.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature, 🎨 Frontend

#266 Feature/#256 chatroom game rule role info popup
  src/main/resources/static/css/basic.css
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature

#273 :sparkles: feat: 채팅창 디자인 변경
  src/main/resources/static/css/basic.css
  src/main/resources/templates/chat-room.html
Labels: 🎨 Frontend

#272 Feat/#236 night vote result
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/game/DayToNightManager.java
  src/main/java/com/springles/game/NightVoteManager.java
  src/main/java/com/springles/service/GameSessionVoteService.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature, 🎨 Frontend

#275 :bug: fix: 채팅방 코드 중복 수정
  src/main/resources/templates/chat-room.html
Labels: 🐛 BugFix

#276 :sparkles: feat: <참여자 목록 dto 수정, FE 추가>
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/controller/api/MemberController.java
  src/main/java/com/springles/domain/dto/member/PlayerInfoResponse.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature, 🎆 API, 🎨 Frontend

#278 Feature/#277 remove unused files
  src/main/java/com/springles/config/WebSocketStompConfig.java
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/exception/GameEndException.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/game/MessageInterceptor.java
  src/main/java/com/springles/jwt/AccessTokenInterceptor.java
  src/main/java/com/springles/service/RefreshTokenService.java
  src/main/java/com/springles/websocket/WebSocketMapping.java
  src/main/resources/templates/chat.html
  src/main/resources/templates/home.html
  src/main/resources/templates/pages/chatting/chatting.html
  src/main/resources/templates/pages/home/home.html
Labels: 🔧 Refactor

#280 :recycle: refactor: <불필요한 코드와 파일 삭제>
  src/main/java/com/springles/domain/dto/response/GameStatus.java
  src/main/java/com/springles/domain/dto/response/GameStatusKill.java
  src/main/java/com/springles/domain/dto/response/GameStatusKillRes.java
  src/main/java/com/springles/domain/dto/response/GameStatusRes.java
  src/main/java/com/springles/domain/dto/response/SuspectVoteRes.java
  src/main/java/com/springles/game/DayDiscussionManager.java
  src/main/java/com/springles/game/DayEliminationManager.java
  src/main/java/com/springles/game/DayToNightManager.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/game/NightVoteManager.java
  src/main/java/com/springles/repository/VoteRedisRepository.java
  src/main/java/com/springles/repository/VoteRepository.java
Labels: 🔧 Refactor

#281 Fix/#274 boss next level hidden
  src/main/resources/static/css/basic.css
  src/main/resources/templates/member/my-page.html
Labels: 🐛 BugFix

#284 Refactor/#282 member remove unused codes files
  src/main/java/com/springles/config/WebSecurityConfig.java
  src/main/java/com/springles/controller/api/RefreshTokenContoller.java
  src/main/java/com/springles/domain/constants/Role.java
  src/main/java/com/springles/domain/dto/message/RoleExplainMessage.java
  src/main/java/com/springles/exception/constants/ErrorCode.java
  src/main/java/com/springles/jwt/JwtExceptionFilter.java
  src/main/java/com/springles/jwt/JwtExceptionHandlerFilter.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
  src/main/java/com/springles/service/impl/RefreshTokenServiceImpl.java
Labels: 🔧 Refactor

#286 Fix/#285 chatroom add valid sequence
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/domain/dto/chatroom/ChatRoomReqDTO.java
  src/main/resources/templates/home/add.html
Labels: 🐛 BugFix

#288 [Hotfix] chatroom member name fix
  src/main/java/com/springles/config/RedisInitializer.java
  src/main/java/com/springles/domain/dto/member/MemberSimpleProfileResponse.java
  src/main/resources/templates/home/index.html
Labels: ✨ Feature, 🐛 BugFix

#289 Refactor/#247 빠른 입장 수정 / index 리셋 버튼 수정
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/controller/ui/ChatRoomUiController.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/resources/templates/check/confirm.html
  src/main/resources/templates/home/index.html
Labels: 🔧 Refactor

#287 Feat/#283 vote logic auto
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/game/DayDiscussionManager.java
  src/main/java/com/springles/game/DayEliminationManager.java
  src/main/java/com/springles/game/DayToNightManager.java
  src/main/java/com/springles/game/NightVoteManager.java
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature, 🔧 Refactor

#292 :bug: fix: <webSocket 연결 유지>
  src/main/resources/templates/chat-room.html
Labels: 🐛 BugFix

#294 Feature/270 player list design ver2
  src/main/java/com/springles/domain/constants/Level.java
  src/main/java/com/springles/domain/constants/ProfileImg.java
  src/main/resources/static/css/basic.css
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/home/index.html
Labels: ✨ Feature, 🎨 Frontend

#295 Feat/#239 game finish
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/game/DayEliminationManager.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/game/NightVoteManager.java
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature, 🎨 Frontend

#298 Feature/#270 player list design version 4
  src/main/java/com/springles/domain/constants/Level.java
  src/main/java/com/springles/domain/constants/ProfileImg.java
  src/main/resources/static/css/basic.css
  src/main/resources/templates/chat-room.html
Labels: 🎨 Frontend

#299 :sparkles: feat: <중간 pr>
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/game/DayDiscussionManager.java
  src/main/java/com/springles/game/DayEliminationManager.java
  src/main/java/com/springles/game/NightVoteManager.java
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature, 🎨 Frontend

#300 [Refactor] 채팅창 sender를 닉네임으로 변경
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/domain/entity/Player.java
  src/main/java/com/springles/game/GameSessionManager.java
Labels: 🔨 Chore

#302 :bug: fix: 닉네임 중복 설정되지 않도록 수정
  src/main/java/com/springles/domain/dto/member/MemberProfileCreateRequest.java
  src/main/java/com/springles/domain/dto/member/MemberProfileUpdateRequest.java
  src/main/java/com/springles/exception/constants/ErrorCode.java
  src/main/java/com/springles/repository/MemberGameInfoJpaRepository.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
Labels: 🐛 BugFix

#303 :sparkles: feat: <닉네임으로 변경>
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/game/DayDiscussionManager.java
  src/main/resources/templates/chat-room.html
Labels: 🔧 Refactor

#305 :bug: fix: 나가기 버튼 수정
  src/main/resources/templates/chat-room.html
Labels: 🐛 BugFix

#307 :bug: fix: 직업별 메시지 수신 시 메시지 처리 로직 추가
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/resources/templates/chat-room.html
Labels: 🐛 BugFix

#309 Fix/#308 game exit member nickname
  src/main/java/com/springles/controller/message/MessageController.java
  src/main/java/com/springles/game/GameSessionManager.java
Labels: 🐛 BugFix

#311 Fix/#291 header error
  src/main/resources/static/css/basic.css
  src/main/resources/static/images/icon_chatroom_info.png
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home/index.html
Labels: 🐛 BugFix

#313 Feat/#293 game record 중간 pr
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/game/DayDiscussionManager.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
  src/main/resources/templates/chat-room.html
Labels: 🐛 BugFix

#314 Fix/#312 access token reissue standard time
  src/main/java/com/springles/jwt/JwtTokenFilter.java
  src/main/java/com/springles/jwt/JwtTokenUtils.java
  src/main/java/com/springles/service/impl/CookieServiceImpl.java
Labels: 🐛 BugFix

#316 Feature/#310 game ending result
  src/main/java/com/springles/domain/dto/member/MemberProfileResponse.java
  src/main/java/com/springles/domain/dto/member/MemberProfileUpdateRequest.java
  src/main/java/com/springles/domain/entity/GameRecord.java
  src/main/java/com/springles/domain/entity/GameSession.java
  src/main/java/com/springles/domain/entity/MemberGameInfo.java
  src/main/java/com/springles/game/GameSessionManager.java
Labels: ✨ Feature

#317 Feature/#296 chatroom enter exist head change
  src/main/java/com/springles/controller/api/ChatRoomController.java
  src/main/java/com/springles/domain/constants/ResponseCode.java
  src/main/java/com/springles/domain/entity/ChatRoom.java
  src/main/java/com/springles/service/ChatRoomService.java
  src/main/java/com/springles/service/impl/ChatRoomServiceImpl.java
  src/main/resources/templates/chat-room.html
  src/main/resources/templates/home/index.html
Labels: 🎆 API, 🎨 Frontend

#318 Feat/#239 game record re
  src/main/java/com/springles/game/DayEliminationManager.java
  src/main/java/com/springles/game/DayToNightManager.java
  src/main/java/com/springles/game/NightVoteManager.java
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature

#321 Feat/#239 game end final
  src/main/java/com/springles/game/DayToNightManager.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/game/NightVoteManager.java
Labels: ✨ Feature, 🎨 Frontend

#323 Feat/#239 final final final
  src/main/java/com/springles/controller/message/VoteController.java
  src/main/java/com/springles/game/DayToNightManager.java
  src/main/java/com/springles/game/NightVoteManager.java
  src/main/java/com/springles/repository/VoteRepository.java
  src/main/java/com/springles/service/GameSessionVoteService.java
  src/main/java/com/springles/service/impl/GameSessionVoteServiceImpl.java
  src/main/resources/templates/chat-room.html
Labels: ✨ Feature, 🎨 Frontend

#324 Fix/#315 chatroom info modal error
  src/main/resources/static/css/basic.css
  src/main/resources/templates/chat-room.html
Labels: 🐛 BugFix

#326 [Feature] 게임 결과 저장 및 테스트
  src/main/java/com/springles/controller/api/MemberController.java
  src/main/java/com/springles/domain/entity/Member.java
  src/main/java/com/springles/game/DayDiscussionManager.java
  src/main/java/com/springles/game/DayEliminationManager.java
  src/main/java/com/springles/game/DayToNightManager.java
  src/main/java/com/springles/game/GameSessionManager.java
  src/main/java/com/springles/service/MemberService.java
  src/main/java/com/springles/service/impl/MemberServiceImpl.java
Labels: ✨ Feature

#329 :sparkles: feat: <중간 커밋>?
  src/main/java/com/springles/game/DayEliminationManager.java
  src/main/java/com/springles/game/NightVoteManager.java
  src/main/resources/templates/chat-room.html
Labels: 🐛 BugFix

#330 📝 docs: readme 추가
  README.md
Labels: 📑 Docs

#332 :bug: fix: yml파일 원복
  src/main/resources/application-dev.yml
  src/main/resources/application-redis.yml
Labels: 🐛 BugFix

#335 :bug: fix: 환경변수 처리했었던 redis_host, datasource url 을 localhost 로 변경합니다.
  src/main/resources/application-dev.yml
  src/main/resources/application-redis.yml
Labels: 🐛 BugFix
